### ISSUE TITLE
Cannot add child to Parent's belongs_to

### ISSUE THREAD

**Issue by morgz** [petehamilton/citier#15]
Seems a shame you can't do this:

Site.first.products << Book.first

Where 

Site
:has_many :products

Product 
:belongs_to :site

---

And

class Book < Product
  acts_as_citier

Throws an error:

ArgumentError: wrong number of arguments (1 for 0)
    from /Users/danmorgz/.rvm/gems/ruby-1.9.2-p0@rails3/gems/citier-0.1.12/lib/citier/child_instance_methods.rb:3:in `save'
    from /Users/danmorgz/.rvm/gems/ruby-1.9.2-p0@rails3/gems/activerecord-3.0.9/lib/active_record/associations/has_many_association.rb:66:in`insert_record'
    from /Users/danmorgz/.rvm/gems/ruby-1.9.2-p0@rails3/gems/activerecord-3.0.9/lib/active_record/associations/association_collection.rb:136:in `block (3 levels) in <<'
    from /Users/danmorgz/.rvm/gems/ruby-1.9.2-p0@rails3/gems/activerecord-3.0.9/lib/active_record/associations/association_collection.rb:480:in`add_record_to_target_with_callbacks'

**Comment by morgz** [comment]
My fork has a fix for this
