### ISSUE TITLE
Redundant pg gem dependecy.

### ISSUE THREAD

**Issue by greyblake** [petehamilton/citier#26]
I use SQLIte3. But when I run an application I got the next exception.

```
/home/spotapov/.rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.18/lib/bundler/rubygems_integration.rb:143:in `block in replace_gem': pg is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
    from /home/spotapov/.rvm/gems/ruby-1.9.2-p180/gems/activerecord-3.1.0/lib/active_record/connection_adapters/postgresql_adapter.rb:6:in `<top (required)>'
    from /home/spotapov/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:240:in `require'
    from /home/spotapov/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:240:in `block in require'
    from /home/spotapov/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:223:in `block in load_dependency'
    from /home/spotapov/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:640:in `new_constants_in'
    from /home/spotapov/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:223:in `load_dependency'
    from /home/spotapov/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:240:in `require'
    from /home/spotapov/.rvm/gems/ruby-1.9.2-p180/gems/citier-0.1.12/lib/citier/sql_adapters.rb:11:in `<top (required)>'
    from /home/spotapov/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:240:in `require'
    from /home/spotapov/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:240:in `block in require'
    from /home/spotapov/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:223:in `block in load_dependency'
    from /home/spotapov/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:640:in `new_constants_in'
    from /home/spotapov/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:223:in `load_dependency'
    from /home/spotapov/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:240:in `require'
    from /home/spotapov/.rvm/gems/ruby-1.9.2-p180/gems/citier-0.1.12/lib/citier.rb:24:in `<top (required)>'
    from /home/spotapov/.rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.18/lib/bundler/runtime.rb:68:in `require'
    from /home/spotapov/.rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.18/lib/bundler/runtime.rb:68:in `block (2 levels) in require'
    from /home/spotapov/.rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.18/lib/bundler/runtime.rb:66:in `each'
    from /home/spotapov/.rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.18/lib/bundler/runtime.rb:66:in `block in require'
    from /home/spotapov/.rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.18/lib/bundler/runtime.rb:55:in `each'
    from /home/spotapov/.rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.18/lib/bundler/runtime.rb:55:in `require'
    from /home/spotapov/.rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.18/lib/bundler.rb:120:in `require'
    from /home/spotapov/poligon/rails/mti_citier/config/application.rb:13:in `<top (required)>'
    from /home/spotapov/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.1.0/lib/rails/commands.rb:38:in `require'
    from /home/spotapov/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.1.0/lib/rails/commands.rb:38:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

If I add `gem 'pg'` to Gemfile and do `bundle install` it works fine. But it's redendant when I do not use PostgreSQL.
## Environment
- rails 3.1 (stable)
- ruby 1.9.2p180

**Comment by axsuul** [comment]
Yep, I can confirm that this is a rails 3.1 issue.

**Comment by DouweM** [comment]
Fixed in pull request #31, commit f6d8abd.

**Comment by warmwaffles** [comment]
Any way you could push this out?

**Comment by petehamilton** [comment]
I merged the code with the main branch, should be fine...
