### ISSUE TITLE
Doesn't work with Heroku

### ISSUE THREAD

**Issue by WontSeeMeComin** [petehamilton/citier#33]
This gem seems to require the sqlite3 gem to also be bundled, but Heroku us unable to successfully compile the sqlite3 gem, so the application fails to start with the following trace:

```
2011-10-16T22:55:43+00:00 app[web.1]: /app/vendor/bundle/ruby/1.9.1/gems/bundler-1.1.rc/lib/bundler/rubygems_integration.rb:143:in `block in replace_gem': sqlite3 is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
2011-10-16T22:55:43+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.1.1.rc3/lib/active_record/connection_adapters/sqlite3_adapter.rb:3:in `<top (required)>'
2011-10-16T22:55:43+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/activesupport-3.1.1.rc3/lib/active_support/dependencies.rb:240:in `require'
2011-10-16T22:55:43+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/activesupport-3.1.1.rc3/lib/active_support/dependencies.rb:240:in `block in require'
2011-10-16T22:55:43+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/activesupport-3.1.1.rc3/lib/active_support/dependencies.rb:223:in `block in load_dependency'
2011-10-16T22:55:43+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/activesupport-3.1.1.rc3/lib/active_support/dependencies.rb:640:in `new_constants_in'
2011-10-16T22:55:43+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/activesupport-3.1.1.rc3/lib/active_support/dependencies.rb:223:in `load_dependency'
2011-10-16T22:55:43+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/activesupport-3.1.1.rc3/lib/active_support/dependencies.rb:240:in `require'
2011-10-16T22:55:43+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/citier-0.1.12/lib/citier/sql_adapters.rb:10:in `<top (required)>'
```

Is there any way around this?

**Comment by WontSeeMeComin** [comment]
Sorry guys, didn't see the commit that fixed this. In case anyone finds this, use on Heroku by grabbing the forked master with fix and including it in Bundler using :path=>"vendor/gems/[gem folder]"
